export const initialDataOrder: OrderFull = {
    "id": 0,
    "price_items": 0,
    "price_total": 0,
    "price_promo": 0,
    "price_delivery": 0,
    "price_exchange": 0,
    "to_commune_name": "",
    "tracking": null,
    "platform": null,
    "label": null,
    "to_wilaya_name": "",
    "address": "",
    "fullName": "",
    "firstname": "",
    "familyname": "",
    "email": "",
    "contact_phone": "",
    "weight": "0",
    "width": 0,
    "height": 0,
    "length": 0,
    "do_insurance": false,
    "freeshipping": false,
    "is_stopdesk": false,
    "ProductStock": false,
    "stopdesk_id": 0,
    "duplicate": 0,
    "address_lat": 0,
    "address_lng": 0,
    "has_exchange": false,
    "state": "pending",
    "product_to_collect": null,
    "nots": "",
    "date_delivery": null,
    "currency": "DZD",
    "CompareAtPrice": 0,
    "created_at": "",
    "updated_at": "",
    "coupon": null,
    "item": [
    ],
    "states": [
    ]
  }