const orderCols= [
    {
        label:"action",
        value:"actions",
        check:true
    },
    {
        label:"name",
        value:"name",
        check:true
    },
    {
        label:"contact_phone",
        value:"contact_phone",
        check:true
    },
    {
        label:"to_wilaya_name",
        value:"to_wilaya_name",
        check:true
    },
    {
        label:"to_commune_name",
        value:"to_commune_name",
        check:true
    },
    {
        label:"Associate",
        value:"associate",
        check:true
    },
    {
        label:"tracking",
        value:"tracking",
        check:true
    },
    {
        label:"products",
        value:"products",
        check:true
    },
    {
        label:"price_total",
        value:"price_total",
        check:true
    },
    {
        label:"state",
        value:"state",
        check:true
    },
    {
        label:"created_at",
        value:"created_at",
        check:true
    },
    
]
export default orderCols